// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace Web_Projekat.Migrations
{
    [DbContext(typeof(VideoKlubContext))]
    [Migration("20211106014324_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Clanovi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Broj_clanske_karte")
                        .HasColumnType("int");

                    b.Property<string>("Datum_isteka_clanarine")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("DiskoviID")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prezime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("DiskoviID");

                    b.ToTable("Clanovi");
                });

            modelBuilder.Entity("Models.Diskovi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Clan_koji_je_pozajmio_disk")
                        .HasColumnType("int");

                    b.Property<int>("Film_na_disku")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Diskovi");
                });

            modelBuilder.Entity("Models.Film", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DiskoviID")
                        .HasColumnType("int");

                    b.Property<string>("Dobijene_nagrade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Godina")
                        .HasColumnType("int");

                    b.Property<string>("Naslov")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nominacija_za_nagrade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Rejting")
                        .HasColumnType("int");

                    b.Property<int>("Reziser")
                        .HasColumnType("int");

                    b.Property<string>("Tip")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UlogeID_filma")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DiskoviID");

                    b.HasIndex("UlogeID_filma");

                    b.ToTable("Filmovi");
                });

            modelBuilder.Entity("Models.Glumci", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prezime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UlogeID_filma")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UlogeID_filma");

                    b.ToTable("Glumci");
                });

            modelBuilder.Entity("Models.Reziseri", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FilmID")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prezime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("FilmID");

                    b.ToTable("Reziseri");
                });

            modelBuilder.Entity("Models.Uloge", b =>
                {
                    b.Property<int>("ID_filma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ID_glumca")
                        .HasColumnType("int");

                    b.Property<string>("Tip_uloge")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID_filma");

                    b.ToTable("Uloge");
                });

            modelBuilder.Entity("Models.Clanovi", b =>
                {
                    b.HasOne("Models.Diskovi", "Diskovi")
                        .WithMany("Clanovi")
                        .HasForeignKey("DiskoviID");

                    b.Navigation("Diskovi");
                });

            modelBuilder.Entity("Models.Film", b =>
                {
                    b.HasOne("Models.Diskovi", "Diskovi")
                        .WithMany("Filmovi")
                        .HasForeignKey("DiskoviID");

                    b.HasOne("Models.Uloge", "Uloge")
                        .WithMany("FilmUloga")
                        .HasForeignKey("UlogeID_filma");

                    b.Navigation("Diskovi");

                    b.Navigation("Uloge");
                });

            modelBuilder.Entity("Models.Glumci", b =>
                {
                    b.HasOne("Models.Uloge", "Uloge")
                        .WithMany("GlumciUloga")
                        .HasForeignKey("UlogeID_filma");

                    b.Navigation("Uloge");
                });

            modelBuilder.Entity("Models.Reziseri", b =>
                {
                    b.HasOne("Models.Film", "Film")
                        .WithMany("Reziseri")
                        .HasForeignKey("FilmID");

                    b.Navigation("Film");
                });

            modelBuilder.Entity("Models.Diskovi", b =>
                {
                    b.Navigation("Clanovi");

                    b.Navigation("Filmovi");
                });

            modelBuilder.Entity("Models.Film", b =>
                {
                    b.Navigation("Reziseri");
                });

            modelBuilder.Entity("Models.Uloge", b =>
                {
                    b.Navigation("FilmUloga");

                    b.Navigation("GlumciUloga");
                });
#pragma warning restore 612, 618
        }
    }
}
